### ISSUE TITLE
Default install obtains the wrong confdir

### ISSUE THREAD

**Issue by slamble** [jessereynolds/puppet-pe_nc_backup#4]
On a fresh install of Puppet Enterprise (verified on 2019.8), configuring this module on the Puppet Master with no parameters causes breakage. The error message seen when running the cron job manually as `pe-puppet` (as the cron job is set up for `pe-puppet`) is:

```
INFO - Running command: [/opt/puppetlabs/puppet/bin/ncio --uri 'https://puppetmaster.localdomain:4433/classifier-api/v1' --cert '/opt/puppetlabs/server/data/puppetserver/.puppetlabs/etc/puppt/ssl/certs/puppetmaster.localdomain.pem' --key '/opt/puppetlabs/server/data/puppetserver/.puppetlabs/etc/puppet/ssl/private_keys/puppetmaster.localdomain.pem' backup > '/opt/pe_nc_backup/repo/node_groups.json']
INFO - ERROR: No such file or directory @ rb_sysopen - /opt/puppetlabs/server/data/puppetserver/.puppetlabs/etc/puppet/ssl/certs/puppetmaster.localdomain.pem
```

Clearly, when the script tries to find the ssldir (`puppet config print ssldir`), it's using the non-root confdir of `~/.puppetlabs/etc/puppet` (where ~ is the home directory of the pe-puppet user: `/opt/puppetlabs/server/data/puppetserver`) rather than the correct system confdir of `/etc/puppetlabs/puppet`.

I haven't - yet - dug into the best way to deal with this; putting the crontab entry in root's crontab would be the simplest choice, but is less than ideal from a security point of view.

**Comment by albatrossflavour** [comment]
I noticed the same thing and have created a [fork](https://github.com/albatrossflavour/puppet-pe_nc_backup/tree/bugfix/ssldir_incorrect) to address it.  Turns the backup script into a template and slots in the ssldir looked up from facter but can be overridden

**Comment by slamble** [comment]
That fix looks solid to me. Apologies; I forgot about digging into this issue in the press of other things that I was dealing with at the client where we found the problem, and didn't follow up when I had the time.

**Comment by jessereynolds** [comment]
Thanks for the bug report @slamble and for the fix @albatrossflavour - this is merged
